### ISSUE TITLE
Shouldn't the previous displacement result be restored to the current scale first?

### ISSUE THREAD

**Issue by Henning742** [ericPrince/optical-flow#3]
https://github.com/ericPrince/optical-flow/blob/af51e0ef10d44101df6e20964759a3728e46f8f8/compare_to_opencv.py#LL103C13-L103C13

Since the previous displacement result is calculated in a downscaled image, the value of displacement will also be shrunk to a smaller scale. I guess we should restore it to the same scale as the current pyramid layer.

Propose to change it to:
```python
d = d[: pyr1.shape[0], : pyr2.shape[1]] * 2
```

**Comment by ericPrince** [comment]
Ha good catch thanks, you're absolutely right!
